version: "3.4"

services:
  pythonrpcserver:
    build:
      context: .
      dockerfile: ./pythonrpcserver.Dockerfile
    container_name: "pythonrpcserver"
    env_file:
      - "config.env"
    environment: 
      - "DEV_MODE=DOCKER"
      - TEST_SIGN_IN=true
    volumes:
        - "./docker_data/data:/data"
    ports:
      - "127.0.0.1:50051:50051"
  
  api:
    # localhost:5080/swag
    build:
      context: .
      target: publish
      dockerfile: ./API.Dockerfile
    volumes:
      - "./docker_data/data:/data"
    container_name: "api"
    depends_on:
      - db
      - rabbitmq
      - elasticsearch
    env_file:
      - "config.env"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DEV_ENV=DOCKER
      - TEST_SIGN_IN=true
      - ASPNETCORE_URLS=http://+:80
    labels:
      - "traefik.enable=true"
      - "traefik.backend=api"
      - "traefik.port=80"
      - "traefik.frontend.rule=PathPrefix: /api/,/data/,/swag"
    command: "/wait-for rabbitmq:5672 --timeout=50 -- dotnet /app/ClassTranscribeServer.dll"

  taskengine:
    build:
      context: .
      target: publish
      dockerfile: ./TaskEngine.Dockerfile

    #image: classtranscribe/taskengine:latest
    volumes:
      - "./docker_data/data:/data"
    container_name: "taskengine"
    depends_on:
      - db
      - rabbitmq
      - pythonrpcserver
      - elasticsearch
    env_file:
      - "config.env"
    environment: 
      - DEV_ENV=DOCKER
      - TEST_SIGN_IN=true
    command: "/wait-for rabbitmq:5672 --timeout=50 -- dotnet /app/TaskEngine.dll"
   
  
  frontend:
    image: classtranscribe/frontend:latest
    env_file:
      - "config.env"
    container_name: "frontend"
    
  db:
    image: postgres:11.7
    volumes:
      - "./docker_data/postgres:/pgdata"
    ports:
      - "127.0.0.1:5432:5432"
    env_file:
      - "config.env"
    environment:
      - PGDATA=/pgdata/data
      - POSTGRES_DB=ct
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ctpass}
    container_name: "db"

# pgadmin is a standalone web application to browse the database
  pgadmin:
    container_name: "pgadmin"
    image: dpage/pgadmin4:latest
    depends_on:
      - db
    volumes:
      - "./docker_data/pgadmin:/var/lib/pgadmin"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=pgadmin"
      - "traefik.port=80"
      - "traefik.frontend.rule=PathPrefix:/pgadmin"
    env_file:
      - "config.env"
    environment:
      # To update default email and password delete the contents of ./docker_data/pgadmin
      - PGADMIN_DEFAULT_EMAIL=a@a
      - PGADMIN_DEFAULT_PASSWORD=ctpass
      #- PGADMIN_LISTEN_PORT=80
      - SCRIPT_NAME=/pgadmin
      - MASTER_PASSWORD_REQUIRED=False


  rabbitmq:
    container_name: "rabbitmq"
    image: rabbitmq:management
    env_file:
      - "config.env"
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management path_prefix "/rabbitmq"
      - RABBITMQ_DEFAULT_USER=ctdev
      - RABBITMQ_DEFAULT_PASS=ctpass
    labels:
      - "traefik.enable=true"
      - "traefik.backend=rabbitmq"
      - "traefik.port=15672"
      - "traefik.frontend.rule=PathPrefix:/rabbitmq"
    ports:
      - "127.0.0.1:5672:5672"
      

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.2
    volumes:
      - "./docker_data/elasticsearch:/usr/share/elasticsearch/data"
    environment:
      - discovery.type=single-node   
    ports:
      - "127.0.0.1:9200:9200"
      #- "127.0.0.1:9300:9300"

  traefik:
    image: traefik:v1.7
    command:
      - --loglevel=INFO
      - --api
      # Entrypoints
      - --defaultentrypoints=https,http
      - --entryPoints=Name:http Address::5000 Redirect.EntryPoint:https
      - --entryPoints=Name:https Address::5443 TLS
      # DOCKER
      - --docker=true
      - --docker.endpoint=unix:///var/run/docker.sock
      - --docker.exposedbydefault=false
      - --docker.watch=true
    ports:
      - "127.0.0.1:5000:5000"
      - "127.0.0.1:5443:5443"
    labels:
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.port=8080"
      - "traefik.frontend.rule=PathPrefixStrip:/traefik"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      #- ./docker_data/traefik/config:/config
    container_name: "traefik"

