name: Docker rpcbase Image

on:
  push:
    branches:
      - master
      - staging
      - expt

  # this runs every day at midnight UTC
  schedule:
    - cron: '0 0 * * *'

# Certain actions will only run when this is the master repo.
env:
  MASTER_REPO: classtranscribe/WebAPI
  DOCKERHUB_ORG: classtranscribe

jobs:
  rpcbase:
    if: github.repository == ${MASTER_REPO}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        branch:
          - master
          - staging
          - expt
        include:
          - branch: master
            tags: latest
          - branch: staging
            tags: staging
          - branch: expt
            tags: expt

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      # this will publish to the actor (person) github packages
      - name: Publish to GitHub
        if: github.event_name == 'push' && github.repository == env.MASTER_REPO
        uses: elgohr/Publish-Docker-Github-Action@2.22
        env:
          BRANCH: ${{ matrix.branch }}
          BUILDNUMBER: ${{ github.run_number }}
          GITSHA1: ${{ github.sha  }}
        with:
          registry: ghcr.io
          name: ${{ github.repository_owner }}/rpcbase
          context: PythonRpcServer
          dockerfile: Dockerfile.base
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASSWORD }}
          tags: "${{ matrix.tags }}"
          buildargs: BRANCH,BUILDNUMBER,GITSHA1

      # this will publish to the clowder dockerhub repo
      - name: Publish latest base to Docker Hub
        uses: elgohr/Publish-Docker-Github-Action@2.22
        env:
          BRANCH: ${{ matrix.branch }}
          BUILDNUMBER: ${{ github.run_number }}
          GITSHA1: ${{ github.sha  }}
        with:
          name: ${{ env.DOCKERHUB_ORG }}/rpcbase
          context: PythonRpcServer
          dockerfile: Dockerfile.base
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          tags: "${{ matrix.tags }}"
          buildargs: BRANCH,BUILDNUMBER,GITSHA1
